"""init_all_tables

Revision ID: b66a9843ecc3
Revises: 
Create Date: 2026-07-07 12:22:43.888618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66a9843ecc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_stock',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('bid_ask_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_auction_date_code', 'auction_stock', ['trade_date', 'code'], unique=True)
    op.create_index(op.f('ix_auction_stock_trade_date'), 'auction_stock', ['trade_date'], unique=False)
    op.create_table('broken_board_pool',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('broken_count', sa.Integer(), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bb_date_code', 'broken_board_pool', ['trade_date', 'code'], unique=True)
    op.create_index(op.f('ix_broken_board_pool_trade_date'), 'broken_board_pool', ['trade_date'], unique=False)
    op.create_table('capital_flow',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('main_net', sa.BigInteger(), nullable=True),
    sa.Column('super_large_net', sa.BigInteger(), nullable=True),
    sa.Column('large_net', sa.BigInteger(), nullable=True),
    sa.Column('medium_net', sa.BigInteger(), nullable=True),
    sa.Column('small_net', sa.BigInteger(), nullable=True),
    sa.Column('main_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cf_date_code', 'capital_flow', ['trade_date', 'code'], unique=True)
    op.create_index(op.f('ix_capital_flow_trade_date'), 'capital_flow', ['trade_date'], unique=False)
    op.create_table('daily_kline',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kline_code_date', 'daily_kline', ['code', 'trade_date'], unique=True)
    op.create_table('dragon_tiger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('buy_amount', sa.BigInteger(), nullable=True),
    sa.Column('sell_amount', sa.BigInteger(), nullable=True),
    sa.Column('net_amount', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dt_date_code', 'dragon_tiger', ['trade_date', 'code'], unique=False)
    op.create_index(op.f('ix_dragon_tiger_trade_date'), 'dragon_tiger', ['trade_date'], unique=False)
    op.create_table('emotion_cycle',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('limit_up_count', sa.Integer(), nullable=True),
    sa.Column('limit_down_count', sa.Integer(), nullable=True),
    sa.Column('broken_board_count', sa.Integer(), nullable=True),
    sa.Column('seal_rate', sa.Float(), nullable=True),
    sa.Column('emotion_score', sa.Float(), nullable=True),
    sa.Column('cycle_phase', sa.String(length=20), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date')
    )
    op.create_table('limit_down_pool',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('circulating_cap', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('consecutive', sa.Integer(), nullable=True),
    sa.Column('seal_amount', sa.BigInteger(), nullable=True),
    sa.Column('board_amount', sa.BigInteger(), nullable=True),
    sa.Column('broken_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ld_date_code', 'limit_down_pool', ['trade_date', 'code'], unique=True)
    op.create_index(op.f('ix_limit_down_pool_trade_date'), 'limit_down_pool', ['trade_date'], unique=False)
    op.create_table('limit_up_pool',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('circulating_cap', sa.BigInteger(), nullable=True),
    sa.Column('total_cap', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('first_seal_time', sa.String(length=20), nullable=True),
    sa.Column('last_seal_time', sa.String(length=20), nullable=True),
    sa.Column('seal_amount', sa.BigInteger(), nullable=True),
    sa.Column('consecutive', sa.Integer(), nullable=True),
    sa.Column('broken_count', sa.Integer(), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lu_date_code', 'limit_up_pool', ['trade_date', 'code'], unique=True)
    op.create_index(op.f('ix_limit_up_pool_trade_date'), 'limit_up_pool', ['trade_date'], unique=False)
    op.create_table('market_snapshot',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('amplitude', sa.Float(), nullable=True),
    sa.Column('circulating_cap', sa.BigInteger(), nullable=True),
    sa.Column('total_cap', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snap_date_code', 'market_snapshot', ['trade_date', 'code'], unique=False)
    op.create_index('idx_snap_time', 'market_snapshot', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_market_snapshot_snapshot_at'), 'market_snapshot', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_market_snapshot_trade_date'), 'market_snapshot', ['trade_date'], unique=False)
    op.create_table('risk_alarms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('alarm_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_alarms_trade_date'), 'risk_alarms', ['trade_date'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_code'), 'stocks', ['code'], unique=True)
    op.create_table('strong_pool',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=10), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('amplitude', sa.Float(), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sp_date_code', 'strong_pool', ['trade_date', 'code'], unique=True)
    op.create_index(op.f('ix_strong_pool_trade_date'), 'strong_pool', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strong_pool_trade_date'), table_name='strong_pool')
    op.drop_index('idx_sp_date_code', table_name='strong_pool')
    op.drop_table('strong_pool')
    op.drop_index(op.f('ix_stocks_code'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_risk_alarms_trade_date'), table_name='risk_alarms')
    op.drop_table('risk_alarms')
    op.drop_index(op.f('ix_market_snapshot_trade_date'), table_name='market_snapshot')
    op.drop_index(op.f('ix_market_snapshot_snapshot_at'), table_name='market_snapshot')
    op.drop_index('idx_snap_time', table_name='market_snapshot')
    op.drop_index('idx_snap_date_code', table_name='market_snapshot')
    op.drop_table('market_snapshot')
    op.drop_index(op.f('ix_limit_up_pool_trade_date'), table_name='limit_up_pool')
    op.drop_index('idx_lu_date_code', table_name='limit_up_pool')
    op.drop_table('limit_up_pool')
    op.drop_index(op.f('ix_limit_down_pool_trade_date'), table_name='limit_down_pool')
    op.drop_index('idx_ld_date_code', table_name='limit_down_pool')
    op.drop_table('limit_down_pool')
    op.drop_table('emotion_cycle')
    op.drop_index(op.f('ix_dragon_tiger_trade_date'), table_name='dragon_tiger')
    op.drop_index('idx_dt_date_code', table_name='dragon_tiger')
    op.drop_table('dragon_tiger')
    op.drop_index('idx_kline_code_date', table_name='daily_kline')
    op.drop_table('daily_kline')
    op.drop_index(op.f('ix_capital_flow_trade_date'), table_name='capital_flow')
    op.drop_index('idx_cf_date_code', table_name='capital_flow')
    op.drop_table('capital_flow')
    op.drop_index(op.f('ix_broken_board_pool_trade_date'), table_name='broken_board_pool')
    op.drop_index('idx_bb_date_code', table_name='broken_board_pool')
    op.drop_table('broken_board_pool')
    op.drop_index(op.f('ix_auction_stock_trade_date'), table_name='auction_stock')
    op.drop_index('idx_auction_date_code', table_name='auction_stock')
    op.drop_table('auction_stock')
    # ### end Alembic commands ###
