<template><section class="exec-desk"><div class="exec-heading"><div><span class="exec-eyebrow">MORNING FLOW / 自动纸面执行</span><h2>{{titles[data?.phase]||'策略执行台'}}</h2><p>前晚精选 × 竞价承接 <span>·</span> 最多3只 <span>·</span> T+1以后退出</p></div><button class="wb-button" @click="load">↻ 更新状态</button></div><div class="exec-timeline"><div v-for="(s,i) in steps" :key="s.time" :class="{current:activeStep===i,done:activeStep>i}"><b>{{activeStep>i?'·':'0'+(i+1)}}</b><span>{{s.title}}<small>{{s.time}}</small></span></div></div><p v-if="error" class="wb-notice error">{{error}}</p><div class="exec-bottom"><div class="exec-signals"><div class="wb-panel-title"><h3>主策略 · {{day}}</h3><button class="wb-text-button" @click="$emit('open','strategy')">规则 ↗</button></div><div v-if="!primary.length" class="exec-empty"><span>◎</span><div><strong>{{data?.phase==='review'?'今日没有冻结的主策略入选':'等待满足完整条件'}}</strong><small>{{data?.last_close?.trade_date===day?'今晚备选已冻结，次日竞价后自动核对。':'没有有效名单时保持空仓观察，不用活跃榜补位。'}}</small></div></div><button v-for="r in primary" :key="r.id" class="exec-signal" @click="$emit('stock',r.code)"><div><strong>{{r.name}}</strong><small>{{r.code}} · 竞价 {{r.auction_pct}}%</small></div><div><span :class="['exec-status',r.state]">{{states[r.state]||r.state}}</span><small>{{r.reason}}</small></div></button><div v-if="data?.last_close" class="exec-next"><small>{{data.last_close.trade_date}} 盘后冻结 · 次日备选</small><div><button v-for="r in data.last_close.payload.rows" :key="r.code" @click="$emit('stock',r.code)">{{r.name}} <span>{{r.code}}</span></button><span v-if="!data.last_close.payload.rows.length">无合格备选</span></div></div></div><div class="exec-kpis"><article><small>已核验模拟入场</small><strong>{{data?.counts?.simulated||0}}<em>/ {{primary.length}}</em></strong><span>必须先有实时确认记录</span></article><article><small>主策略 T+1 净变化</small><strong>{{data?.stats?.mean_net_pct==null?'—':data.stats.mean_net_pct+'%'}}</strong><span>{{data?.stats?.count||0}}笔已到期 · 费用已计入</span></article><button @click="$emit('open','replay')">查看回溯与前瞻结果 ↗</button></div></div><details class="exec-note"><summary>执行边界与时点</summary><p>{{data?.note}} 09:35–09:39确认；09:45后的完整K线仅用于核验09:40模拟参考价，并非当时真实成交。实时错过确认的样本不计入主策略前瞻业绩。</p></details></section></template>
<script setup>
import {ref,computed,watch,onUnmounted} from 'vue'
import axios from 'axios'
const props=defineProps({day:String});defineEmits(['open','stock']);const data=ref(),error=ref('');let sequence=0,disposed=false
const states={waiting:'待确认',confirmed:'承接已确认',simulated:'已记录模拟入场',rejected:'未触发',missed:'错过确认',not_entered:'未模拟买入'}
const titles={prepare:'先做计划，等待开盘。',auction:'竞价核对，只留精选。',wait_bar:'等待首根K线，确认承接。',confirm:'早盘确认窗口已开启。',wait_entry:'确认已留痕，等待成交核验。',tracking:'观察入场，记录每个判断。',manage:'入场窗口结束，跟踪持仓。',review:'收盘复盘，为明天做准备。',history:'回看当时的判断与结果。'}
const steps=[{title:'盘后精选',time:'17:30后'},{title:'竞价入选',time:'09:26—09:29'},{title:'承接确认',time:'09:35—09:39'},{title:'模拟入场核验',time:'09:45后'},{title:'结果复核',time:'T+1 / 2 / 3'}]
const activeStep=computed(()=>({prepare:0,auction:1,wait_bar:2,confirm:2,wait_entry:3,tracking:3,manage:4,review:4,history:4}[data.value?.phase]??0))
const primary=computed(()=>(data.value?.items||[]).filter(r=>r.strategy===data.value.primary))
async function load(){const id=++sequence;try{const r=await axios.get('/api/workbench/execution-desk',{params:{day:props.day}});if(id===sequence&&!disposed){data.value=r.data;error.value=''}}catch{if(id===sequence)error.value='执行状态暂不可读'}}
watch(()=>props.day,()=>{data.value=null;load()},{immediate:true});const timer=setInterval(()=>{if(!document.hidden)load()},30000);onUnmounted(()=>{disposed=true;++sequence;clearInterval(timer)})
</script>
