<template><section class="wb-panel"><div class="wb-panel-title"><div><h3>自动观察 · 两组策略对照</h3><small>前晚冻结 → 09:26竞价入选 → 09:40模拟参考 → T+1以后复核</small></div><button class="wb-button small" @click="load">刷新</button></div><p v-if="error" class="wb-notice error">{{ error }}</p><div class="wb-tags"><span>每组最多3只</span><span>普通沪深主板</span><span>模拟 · 不下单</span><span>固定1 / 2 / 3日退出</span></div><p v-if="!report?.batches.length" class="wb-empty">等待今晚17:30后首轮有效盘后数据冻结。明早无合格条件时保持空名单。</p><div class="wb-table-scroll"><table class="wb-table"><thead><tr><th>策略</th><th>持有交易日</th><th>信号 / 可评估</th><th>盈利比例</th><th>平均净变化</th><th>同一批完整样本</th><th>未到期 / 待核验 / 未触发</th></tr></thead><tbody><tr v-for="s in report?.summary" :key="s.strategy+s.hold"><td>{{ s.name }}</td><td>{{ s.hold }}日</td><td>{{ s.signals }} / {{ s.evaluated }}</td><td>{{ pct(s.win_rate) }}</td><td>{{ pct(s.mean_net_pct) }}</td><td>{{ s.common_count }}笔 · {{ pct(s.common_mean) }}</td><td>{{ s.pending }} / {{ s.unknown+s.unresolved_entries }} / {{ s.not_entered }}</td></tr></tbody></table></div><details class="wb-desk-detail"><summary>自动冻结的名单与逐笔结果</summary><div v-for="b in report?.batches" :key="b.trade_date+b.phase"><strong>{{ b.trade_date }} · {{ b.phase==='review'?'盘后备选':'竞价确认' }}</strong><p v-if="b.phase==='review'">{{ b.payload.rows.map(r=>r.name+' '+r.code).join('、') || '没有合格备选' }} · 计划买入 {{ b.payload.window.buy_date }}，最早卖出 {{ b.payload.window.earliest_sell_date }}</p><p v-else>{{ b.payload.signals.map(s=>s.row.name+' ['+(s.strategy==='hot_auction_v1'?'热点':'精选')+']').join('、') || '未满足条件，空名单' }}</p></div><div v-for="s in report?.signals" :key="s.id"><strong>{{ s.trade_date }} {{ s.name }} · {{ s.strategy==='hot_auction_v1'?'热点＋竞价':'精选＋竞价' }}</strong><p>{{ s.result?.reason || '等待收盘核验模拟入场' }}</p><p v-for="p in s.result?.paths" :key="p.hold">{{ p.exit_date || '日历不足' }} · {{ p.hold }}日 · {{ labels[p.status] }} · {{ p.status==='evaluated'?pct(p.net_pct):p.reason }}</p></div></details><p class="wb-footnote">{{ report?.note }} 样本不足时不宣布最佳策略；费用和滑点沿用固定回溯模型。</p></section></template>
<script setup>
import {ref,onMounted,onUnmounted} from 'vue'
import axios from 'axios'
const report=ref(null),error=ref('');let active=true
const labels={pending:'未到期',unknown:'数据待核验',blocked:'卖出受阻',evaluated:'模拟已评估'}
const pct=n=>n==null?'—':Number(n).toFixed(2)+'%'
async function load(){try{const r=await axios.get('/api/workbench/paper-observer');if(active){report.value=r.data;error.value=''}}catch{if(active)error.value='自动观察记录暂不可读'}}
onMounted(load);const timer=setInterval(()=>{if(!document.hidden)load()},60000);onUnmounted(()=>{active=false;clearInterval(timer)})
</script>
