<template><div class="price-chart"><div class="wb-panel-title"><small><span style="color:#e8be70">MA5</span> · <span style="color:#79c9f3">MA10</span> · <span style="color:#cf9df7">MA20</span> · 成交量</small><div class="wb-inline"><button v-for="n in [60,100]" :key="n" class="wb-button small" @click="window=n">{{ n }}日</button></div></div><svg v-if="bars.length" viewBox="0 0 720 280" role="img" aria-label="前复权日K线、5日10日20日均线和成交量"><g v-for="i in 4" :key="i"><line x1="12" :y1="i*40" x2="660" :y2="i*40" stroke="#263144" stroke-dasharray="3 5"/><text x="666" :y="i*40+4" fill="#8793aa" font-size="10">{{ (hi-i*40/180*span).toFixed(2) }}</text></g><g v-for="(b,i) in bars" :key="b.t" :stroke="b.c>=b.o?'#f07879':'#50c7a6'" :fill="b.c>=b.o?'#f07879':'#50c7a6'"><title>{{ b.t }} 开 {{ b.o }} 高 {{ b.h }} 低 {{ b.l }} 收 {{ b.c }} 量 {{ b.v ?? '缺失' }}</title><line :x1="x(i)" :x2="x(i)" :y1="y(b.h)" :y2="y(b.l)"/><rect :x="x(i)-width/2" :y="Math.min(y(b.o),y(b.c))" :width="width" :height="Math.max(1,Math.abs(y(b.o)-y(b.c)))" stroke="none"/><rect v-if="b.v!=null" :x="x(i)-width/2" :y="250-b.v/maxVolume*40" :width="width" :height="b.v/maxVolume*40" stroke="none" opacity=".65"/></g><path v-for="(n,i) in [5,10,20]" :key="n" :d="maPath(n)" fill="none" :stroke="['#e8be70','#79c9f3','#cf9df7'][i]" stroke-width="1.3"/><text x="12" y="275" fill="#8793aa" font-size="10">{{ bars[0]?.t }}</text><text x="570" y="275" fill="#8793aa" font-size="10">{{ bars.at(-1)?.t }}</text></svg><div v-else class="wb-empty">日线尚未准备。点击“补齐日线”后查看。</div></div></template>
<script setup>
import {computed,ref} from 'vue'
const props=defineProps({items:{type:Array,default:()=>[]}}),window=ref(60)
const all=computed(()=>[...new Map(props.items.filter(b=>/^\d{4}-\d{2}-\d{2}/.test(String(b.t))&&['o','h','l','c'].every(k=>Number.isFinite(Number(b[k]))&&Number(b[k])>0)&&Number(b.l)<=Math.min(Number(b.o),Number(b.c))&&Number(b.h)>=Math.max(Number(b.o),Number(b.c))).map(b=>[b.t,{...b,o:Number(b.o),h:Number(b.h),l:Number(b.l),c:Number(b.c),v:b.v!=null&&Number.isFinite(Number(b.v))&&Number(b.v)>=0?Number(b.v):null}])).values()].sort((a,b)=>a.t.localeCompare(b.t)))
const bars=computed(()=>all.value.slice(-window.value)),offset=computed(()=>all.value.length-bars.value.length)
const hi=computed(()=>Math.max(...bars.value.map(b=>b.h))*1.015),lo=computed(()=>Math.min(...bars.value.map(b=>b.l))*.985),span=computed(()=>hi.value-lo.value||1),maxVolume=computed(()=>Math.max(1,...bars.value.map(b=>b.v||0)))
const width=computed(()=>Math.max(2,Math.min(8,640/Math.max(bars.value.length,1)*.65)))
const x=i=>12+(i+.5)*640/Math.max(bars.value.length,1),y=v=>(hi.value-v)/span.value*180
function maPath(n){let d='';bars.value.forEach((b,i)=>{const end=offset.value+i;if(end<n-1)return;const avg=all.value.slice(end-n+1,end+1).reduce((s,v)=>s+v.c,0)/n;d+=(d?' L':'M')+x(i)+','+y(avg)});return d}
</script>
