<template>
 <section class="wb-hero"><div><div class="wb-eyebrow">A-SHARE / T+1 RESEARCH</div><h2>今晚缩小范围，明早确认强弱。</h2><p>盘后热点与龙虎榜 → 次日竞价核对 → 9:30—10:00观察入场 → 遵守 T+1 退出。候选依据、历史缺口和成交假设分别保留。</p></div></section>
 <div class="wb-panel-title"><div class="wb-mode"><button :class="{active:tab==='prepare'}" @click="tab='prepare'">次日备选</button><button :class="{active:tab==='recent'}" @click="tab='recent'">近五日回溯</button><button :class="{active:tab==='study'}" @click="tab='study'">持有期研究</button><button :class="{active:tab==='audit'}" @click="tab='audit'">完整接口审计</button></div><button class="wb-button" @click="load">刷新研究结果</button></div>
 <p v-if="error" class="wb-notice error" role="alert">{{ error }}</p><p v-if="message" class="wb-notice" role="status">{{ message }}</p>
 <template v-if="tab==='prepare'">
 <section class="wb-metrics"><article><label>盘后信号日</label><strong>{{ day }}</strong><small>{{ preparation?.provisional?'盘后尚未完成，临时结果':'证据按所选日期隔离' }}</small></article><article><label>计划买入日</label><strong>{{ preparation?.window.buy_date || '日历缺失' }}</strong><small>次一交易日开盘后确认</small></article><article><label>最早卖出日</label><strong>{{ preparation?.window.earliest_sell_date || '日历缺失' }}</strong><small>不能买入当天卖出；周末、休市跳过</small></article><article><label>合并去重候选</label><strong>{{ preparation?.rows.length ?? '—' }}</strong><small>涨停池 ∪ 强势池 ∪ 龙虎榜</small></article></section>
 <section class="wb-panel"><div class="wb-panel-title"><div><h3>资金关注与热点交集</h3><p>{{ preparation?.note }}</p></div><button class="wb-button primary" :disabled="busy" @click="$emit('collect','review')">补齐当日盘后证据</button></div>
 <div class="wb-tags"><span v-for="s in preparation?.sources || []" :key="s.api" :class="['wb-status','status-'+s.status]">{{ s.name }} · {{ status(s.status) }} · {{ s.rows }}条</span></div>
 <p class="wb-footnote">接口约9:26返回的竞价结果，只能用于竞价结束后的确认；不能假定按9:25开盘撮合价买入。当前榜单不能回填历史。17:10只是日线更新参考时间，仍需核对字段和源日期。</p>
 <input v-model="search" placeholder="搜索代码、名称或行业" aria-label="搜索次日备选"/>
 <div class="wb-table-scroll"><table class="wb-table"><thead><tr><th>标的</th><th>证据交集</th><th>热点方向</th><th>成交额 / 参考价</th><th>执行前检查</th><th>计划</th></tr></thead><tbody><tr v-for="r in candidates.slice(0,limit)" :key="r.code"><td><strong>{{ r.name }}</strong><small>{{ r.code }}</small></td><td><div class="wb-tags"><span v-for="reason in r.reasons" :key="reason">{{ reason }}</span></div><small>{{ r.overlap }}项交集；不是胜率</small></td><td>{{ r.industry }}<small>同方向候选 {{ r.industry_count }}只</small></td><td>{{ money(r.amount) }}<small>参考价 {{ r.price ?? '缺失' }}</small></td><td><small v-for="risk in r.risks" :key="risk">{{ risk }}</small></td><td><button class="wb-button small" :disabled="!preparation?.ready_for_decision" @click="freeze(r)">冻结备选</button></td></tr></tbody></table></div>
 <p v-if="!candidates.length" class="wb-empty">所选日期尚无候选证据，请采集盘后数据。不会借用其他日期替代。</p><button v-if="candidates.length>limit" class="wb-button" @click="limit+=30">显示更多（{{ Math.min(limit,candidates.length) }} / {{ candidates.length }}）</button>
 <p class="wb-footnote">历史日期点击冻结，只记录“现在重建的历史候选”，不能冒充当时推荐。当前版本没有真实委托或成交记录。</p></section>
 </template>
 <RecentReplay v-if="tab==='recent'"/>
 <template v-if="tab==='study'"><section class="wb-panel"><h3>持有 1 / 2 / 3 / 5 / 10 个交易日</h3><p class="wb-notice">当前日线研究不能验证“10点前买入更好”，也不能验证竞价策略。需要历史分钟线、带时间戳的信号与可成交证据。</p><p>{{ study?.note }}</p><p v-if="study?.complete" class="wb-notice">源响应内带日期的历史池样本：{{ study.historical_date_verified_samples }} / {{ study.trades?.length }}。未带日期的样本仅依赖请求参数，以下为有条件的探索性结果。</p><p class="wb-rules">持有1日 = 买入后的下一交易日退出。盘后信号 D → D+1 开盘买入 → 最早 D+2 卖出。不同持有期需要同一批成熟样本比较；不能把重叠交易的平均涨幅当作账户收益。</p>

 <div v-if="study?.comparisons?.length" class="wb-table-scroll"><table class="wb-table"><thead><tr><th>持有期</th><th>可评估 / 候选</th><th>平均价格变化</th><th>价格上涨比例</th></tr></thead><tbody><tr v-for="r in study.comparisons" :key="r.hold"><td>{{ r.hold }}交易日</td><td>{{ r.count }} / {{ r.total }}</td><td>{{ r.mean_pct==null?'证据不足':r.mean_pct+'%' }}</td><td>{{ r.win_rate==null?'—':r.win_rate+'%' }}</td></tr></tbody></table></div>
 <details><summary>展开历史接口覆盖明细</summary> <div class="wb-table-scroll"><table class="wb-table"><thead><tr><th>信号日期</th><th>接口</th><th>结果</th><th>记录数</th><th>源日期检查</th></tr></thead><tbody><tr v-for="(r,i) in study?.coverage || []" :key="i"><td>{{ r.day }}</td><td>{{ r.api }}</td><td>{{ status(r.status) }}</td><td>{{ r.rows }}</td><td>{{ r.date_check }}</td></tr></tbody></table></div></details>
 <details><summary>展开逐笔价格路径与剔除原因</summary><div class="wb-table-scroll"><table class="wb-table"><thead><tr><th>信号 / 标的</th><th>核验状态</th><th>持有期：参考买入 → 参考退出 / 变化</th></tr></thead><tbody><tr v-for="(t,i) in study?.trades || []" :key="i"><td>{{ t.signal_date }}<small>{{ t.name }} {{ t.code }}</small></td><td>{{ t.status==='evaluated'?'路径完整，成交未核验':t.reason }}</td><td><small v-for="p in t.paths || []" :key="p.hold">{{ p.hold }}日：{{ p.entry_date }} {{ p.entry_price }} → {{ p.exit_date }} {{ p.exit_price }} / {{ p.price_change_pct }}%</small></td></tr></tbody></table></div></details>
 <p class="wb-footnote">若缺少历史竞价、完整交易日、涨跌停价、停牌或复权证据，不能认定策略可成交。研究收益不等于实盘收益，持续盈利无法保证。</p></section></template>
 <template v-if="tab==='audit'"><section class="wb-panel"><div class="wb-panel-title"><div><h3>量脉目录审计 {{ audit?.completed || 0 }} / {{ audit?.total || 255 }}</h3><p>{{ audit?.scope }}</p></div><select v-model="auditFilter" aria-label="筛选接口状态"><option value="all">全部状态</option><option value="error">请求失败</option><option value="empty">返回为空</option><option value="ready">返回数据</option><option value="untested">未实测</option></select></div><div class="wb-tags"><span v-for="(v,k) in audit?.counts || {}" :key="k">{{ status(k) }} {{ v }}</span></div><p class="wb-footnote">样本日期 {{ audit?.sample_date }}；目录样本用于检测连通与响应结构，不代表全部股票或历史字段均可用。历史参数只表示文档可传参，不证明服务端执行了日期过滤。</p>
 <div class="wb-table-scroll"><table class="wb-table"><thead><tr><th>接口</th><th>样本结果</th><th>记录 / 键数</th><th>历史参数</th><th>返回日期范围</th></tr></thead><tbody><tr v-for="r in audited" :key="r.api"><td><strong>{{ r.name }}</strong><small>{{ r.api }}</small></td><td><span :class="['wb-status','status-'+r.status]">{{ status(r.status) }}</span><small v-if="r.status==='error'||r.status==='untested'">{{ r.reason }}</small></td><td>{{ r.rows_or_keys ?? '—' }}</td><td>{{ r.history_parameters.join(', ') || '无日期参数' }}</td><td>{{ r.first_date || '未识别' }}<small>{{ r.last_date || '' }}</small></td></tr></tbody></table></div></section></template>
</template>
<script setup>
import {ref,computed,watch} from 'vue'
import axios from 'axios'
import RecentReplay from './RecentReplay.vue'
const props=defineProps({day:String,mode:String,busy:Boolean});defineEmits(['collect'])
const tab=ref('prepare'),preparation=ref(null),audit=ref(null),study=ref(null),error=ref(''),message=ref(''),search=ref(''),limit=ref(30),auditFilter=ref('all');let seq=0
const status=s=>({ready:'返回数据',empty:'返回为空',error:'请求失败',untested:'未实测',local:'本地降级'})[s]||s
const money=n=>n==null?'缺失':(n/1e8).toFixed(2)+'亿'
const candidates=computed(()=>(preparation.value?.rows||[]).filter(r=>`${r.code} ${r.name} ${r.industry}`.includes(search.value.trim())))
const audited=computed(()=>(audit.value?.items||[]).filter(r=>auditFilter.value==='all'||r.status===auditFilter.value))
async function load(){const id=++seq;error.value='';try{const results=await Promise.all([axios.get('/api/workbench/preparation',{params:{day:props.day}}),axios.get('/api/workbench/interface-audit'),axios.get('/api/workbench/history-study')]);if(id!==seq)return;[preparation.value,audit.value,study.value]=results.map(r=>r.data)}catch{if(id===seq)error.value='研究数据读取失败，请刷新或确认服务状态。'}}
async function freeze(r){try{const res=await axios.post('/api/workbench/preparation/plans',{day:props.day,code:r.code,mode:props.mode,phase:'review',note:'盘后候选；次日竞价及开盘成交条件待确认'});message.value=res.data.message}catch(e){message.value=e.response?.data?.detail || '冻结失败，请重新核对数据'}}
watch(()=>props.day,()=>{preparation.value=null;limit.value=30;load()},{immediate:true})
watch(()=>props.busy,(v,old)=>{if(old&&!v)load()})
</script>
