<template>
  <div class="wb-shell">
    <aside class="wb-sidebar">
      <a class="wb-brand" href="/"><span class="wb-brand-mark">脉</span><div>观脉 <small>MARKET OBSERVATORY</small></div></a>
      <div class="wb-workspace"><span class="wb-dot"></span> 本地研究工作台 <small>V4.2 / 短线工作流</small></div>
      <div class="wb-nav-label">交易研究</div>
      <button v-for="n in navigation" :key="n.key" :class="['wb-nav',{active:page===n.key}]" @click="page=n.key"><span>{{ n.icon }}</span>{{ n.name }}<small v-if="n.key==='plans'">{{ plans.length }}</small></button>
      <div class="wb-sidebar-bottom"><div class="wb-nav-label">工作原则</div><p>先看环境，再选标的<br>每个分数，都能追溯<br>每次观察，留下依据</p><div class="wb-local">● 本机数据 · 凭证仅在后端</div></div>
    </aside>
    <main class="wb-main">
      <header class="wb-header"><div><span class="wb-eyebrow">{{ phaseLabel }} / {{ mode==='short' ? 'SHORT TERM' : 'TREND RESEARCH' }}</span><h1>{{ navigation.find(n=>n.key===page)?.name }}</h1></div>
        <div class="wb-header-actions"><label class="wb-auto"><input type="checkbox" v-model="autoSync"/>盘中60秒更新</label><input aria-label="研究日期" type="date" v-model="day" @change="reloadAll" :max="today"/><span class="wb-mode"><button :class="{active:mode==='short'}" @click="setMode('short')">短线</button><button :class="{active:mode==='trend'}" @click="setMode('trend')">趋势</button></span><button class="wb-button primary" :disabled="busy" @click="collect(phase)">{{ busy ? '采集中…' : '↻ 同步'+phaseName(phase)+'数据' }}</button></div>
      </header>
      <div v-if="['screen','review'].includes(page)" class="wb-phasebar"><button v-for="(p,i) in phases" :key="p.key" :class="{active:phase===p.key}" @click="setPhase(p.key)"><b>0{{ i+1 }}</b><span>{{ p.title }}<small>{{ p.subtitle }}</small></span><em v-if="i<2">→</em></button><div class="wb-phase-status"><span class="wb-dot"></span>{{ data?.previous_date ? '前一交易日 '+data.previous_date : '交易日历待准备' }}</div></div>
      <div v-if="data?.entry_policy" class="wb-notice"><strong>{{ entryLabel }}</strong><span> · 默认短线/超短，买入后最早下一交易日卖出。</span></div>
      <div v-if="message" class="wb-notice" role="status">{{ message }}<button @click="message=''">×</button></div>
      <div v-if="error" class="wb-notice error" role="alert">{{ error }} <button @click="reloadAll">重试</button></div>
      <div v-if="job && busy" class="wb-job"><span class="wb-spinner"></span><b>正在核对接口与写入数据</b><span>{{ job.progress }}/{{ job.total || '…' }}</span><progress :value="job.progress" :max="job.total || 1"/></div>

      <template v-if="page==='screen' || page==='review'">
        <section class="wb-hero"><div><div class="wb-eyebrow">{{ mode==='short' ? '从盘面中找到值得跟踪的线索' : '让历史结构与当下价格相互验证' }}</div><h2>{{ phase==='pre' ? '盘前有计划，盘中有依据。' : phase==='review' ? '回看结果，更要回看当时的判断。' : mode==='short' ? '看清盘面，缩小你的关注范围。' : '过滤短时波动，观察趋势结构。' }}</h2><p>{{ phase==='pre' ? '竞价排行是截面证据，约9:26后可用；不混入盘中价格。' : mode==='trend' ? '使用前一交易日前的前复权日线，65条不足不评分。先选范围，再补齐日线。' : '成交、量比、涨幅与开盘承接共同排序。可筛选、可解释、可冻结观察。' }}</p></div><div class="wb-hero-count"><span>已核验候选</span><strong>{{ number(data?.total || 0) }}</strong><small>{{ data?.scored || 0 }} 只可计算完整规则分</small></div></section>
        <section class="wb-metrics">
          <article><label>{{ phase==='pre' ? '抢筹上涨 / 下跌' : '上涨 / 下跌' }}</label><strong><span class="wb-up">{{ data?.market.up ?? '—' }}</span><em>/</em><span class="wb-down">{{ data?.market.down ?? '—' }}</span></strong><small>{{ phase==='pre' ? '本批竞价排行统计' : '本批股票快照统计' }}</small></article>
          <article><label>{{ phase==='pre' ? '前日涨停 / 跌停' : '涨停 / 跌停' }}</label><strong>{{ data?.market.limit_up ?? '—' }}<em>/</em>{{ data?.market.limit_down ?? '—' }}</strong><small>独立股池 · {{ data?.context_date }}</small></article>
          <article><label>{{ phase==='pre' ? '前日炸板记录' : '炸板记录' }}</label><strong class="wb-amber">{{ data?.market.broken ?? '—' }}</strong><small>分歧线索，缺失不填零</small></article>
          <article><label>{{ phase==='pre' ? '抢筹成交额' : '成交额' }}</label><strong>{{ amount(data?.market.amount) }}</strong><small>{{ quoteLabel }}</small></article>
        </section>
        <div class="wb-context-grid"><section class="wb-panel"><div class="wb-panel-title"><h3>盘面温度分布</h3><span>按当前快照涨跌幅</span></div><div class="wb-breadth"><div v-for="bin in bins" :key="bin.label"><strong>{{ bin.count }}</strong><div :style="{height:Math.max(3,bin.count/maxBin*55)+'px',background:bin.color}"></div><small>{{ bin.label }}</small></div></div></section>
          <section class="wb-panel"><div class="wb-panel-title"><h3>{{ phase==='pre' ? '竞价方向' : '涨停行业线索' }}</h3><span>{{ phase==='pre' ? '竞价涨幅' : '池内数量，不等于板块强度' }}</span></div><div class="wb-sector-strip"><button v-for="s in sectors" :key="s.name" @click="phase!=='pre' && (industry=industry===s.name?'':s.name)" :class="{selected:industry===s.name}"><span>{{ s.name }}</span><b>{{ s.value }}</b></button><p v-if="!sectors.length" class="wb-muted">该阶段尚无有效板块证据。</p></div></section></div>
      </template>

      <section v-if="page==='screen'" class="wb-panel wb-screen-panel">
        <div class="wb-panel-title"><div><h3>候选标的</h3><span>{{ filtered.length }} 只符合当前条件 · {{ mode==='short' ? '短线规则' : '趋势规则' }}</span></div><div class="wb-inline"><button class="wb-button" @click="resetFilters">重置筛选</button><button class="wb-button" :disabled="busy || !historyCodes.length" @click="collect('history',historyCodes)">补齐待计算20只日线</button></div></div>
        <div class="wb-mode wb-triage"><button :class="{active:tier==='focus'}" @click="tier='focus'">重点观察 {{ focus.length }} / 5</button><button :class="{active:tier==='pending'}" @click="tier='pending'">待确认 · 最多15只</button><button :class="{active:tier==='excluded'}" @click="tier='excluded'">暂不考虑</button><button :class="{active:tier==='all'}" @click="tier='all'">全部 {{ ranked.length }}</button></div><p class="wb-footnote">重点最多5只，同一行业最多2只；不凑数。短线≥65分、趋势≥75分，并核验涨幅、成交活跃度和报价时效。只是研究优先级，不等于可以买入。</p><div class="wb-filterbar"><input aria-label="搜索股票" v-model="search" placeholder="⌕ 代码、名称、概念"/><select aria-label="候选范围" v-model="scope"><option value="all">全部股票</option><option value="pool">今日涨停</option><option value="strong">强势池</option><option value="saved">我的观察</option></select><select aria-label="行业筛选" v-model="industry"><option value="">全部行业</option><option v-for="s in data?.industries || []" :key="s.name">{{ s.name }}</option></select><label><input type="checkbox" v-model="excludeST"/>排除ST / 退市标记</label><button class="wb-preset" @click="preset">{{ mode==='short' ? '应用：活跃强势' : '应用：趋势完整' }}</button></div>
        <div class="wb-filter-numbers"><label>最低规则分 <input aria-label="最低规则分" type="number" min="0" max="100" v-model.number="minScore"/></label><label>{{ phase==='pre' ? '抢筹成交额 ≥' : '成交额 ≥' }} <input aria-label="最低成交额亿元" type="number" min="0" step="0.5" v-model.number="minAmount"/>亿</label><label>{{ phase==='pre' ? '抢筹涨幅' : '涨幅' }} <input aria-label="最低涨幅" type="number" v-model.number="minPct"/>至<input aria-label="最高涨幅" type="number" v-model.number="maxPct"/>%</label><label v-if="phase!=='pre'">量比 ≥ <input aria-label="最低量比" type="number" min="0" step="0.2" v-model.number="minVolume"/></label><button class="wb-text-button" @click="showRules=!showRules">{{ showRules ? '收起' : '查看' }}评分公式 ↗</button></div>
        <div v-if="showRules" class="wb-rules"><strong>规则 {{ data?.rule_version }}</strong><p>{{ mode==='trend' ? 'MA20>MA60：30分；价格>MA20：25分；MA20比五日前上升：25分；价格突破此前20日最高价：20分。日线必须覆盖至前一交易日且至少65条。' : phase==='pre' ? '抢筹成交额÷5000万，上限40分；抢筹涨幅÷5%，上限30分；抢筹委托额÷1亿，上限30分。负值对应0分。' : '成交额÷5亿，上限30分；量比÷3，上限25分；涨幅÷5%，上限25分；价格不低于开盘价20分。前三项均截断至0—各自上限。' }}</p><p>{{ data?.note }} 人气与行业只作旁证，未核验的资金指标不参与评分。</p></div>
        <div v-if="loading" class="wb-empty"><span class="wb-spinner"></span>正在读取本地证据…</div>
        <div v-else-if="!filtered.length" class="wb-empty"><strong>{{ data?.total ? '当前条件没有匹配标的' : '这一阶段还没有可用候选' }}</strong><p>{{ data?.total ? '重点不足不凑数。查看待确认的原因，补齐数据，或切换全部搜索股票。' : '点击右上方同步本阶段数据，查看各接口的真实结果。' }}</p></div>
        <div v-else class="wb-table-scroll"><table class="wb-table"><thead><tr><th>标的 / 方向</th><th><button @click="sort='score'">规则分 ↓</button></th><th>{{ phase==='pre' ? '抢筹涨幅' : '现价 / 涨幅' }}</th><th><button @click="sort='amount'">{{ phase==='pre' ? '抢筹成交额' : '成交额 / 量比' }} ↓</button></th><th>证据与风险</th><th>操作</th></tr></thead><tbody><tr v-for="r in paged" :key="r.code" :class="{selected:selected?.code===r.code}" @click="openStock(r)"><td><strong>{{ r.name }}</strong><small>{{ r.code }} <span>· {{ r.industry }}</span></small></td><td><div class="wb-score"><b>{{ r.score ?? '—' }}</b><div><i :style="{width:(r.score || 0)+'%'}"></i></div></div><small>{{ r.score==null ? '证据待补齐' : '完整规则' }}</small></td><td><strong v-if="phase!=='pre'">{{ price(r.price) }}</strong><span :class="tone(phase==='pre'?r.auction_pct:r.pct_chg)">{{ pct(phase==='pre'?r.auction_pct:r.pct_chg) }}</span></td><td><strong>{{ amount(phase==='pre'?r.auction_amount:r.amount) }}</strong><small v-if="phase!=='pre'">量比 {{ r.volume_ratio ?? '—' }} · 换手 {{ pct(r.turnover) }}</small></td><td><div class="wb-tags"><span v-if="r.in_pool" class="red">{{ phase==='pre' ? '前日涨停' : '涨停池' }} {{ r.consecutive || '' }}</span><span v-if="r.strong">{{ phase==='pre' ? '前日强势' : '强势池' }}</span><span v-if="r.tags?.includes('前日龙虎榜')">前日龙虎榜</span><span v-if="r.popularity">人气 #{{ r.popularity }}</span><span v-if="mode==='trend' && r.trend.ma20" class="green">MA20 {{ r.trend.ma20 }}</span></div><small>{{ r.decision?.reason || r.risks[0] || r.freshness.label }}</small></td><td><button class="wb-button small" @click.stop="savePlan(r)">{{ savedCodes.has(r.code) ? '已观察' : '＋ 观察' }}</button></td></tr></tbody></table></div>
        <div class="wb-pagination"><span>排序仅供研究 · 点击股票查看证据</span><div><button :disabled="pageNumber<=1" @click="pageNumber--">←</button><span>{{ pageNumber }} / {{ pageCount }}</span><button :disabled="pageNumber>=pageCount" @click="pageNumber++">→</button></div></div>
      </section>

      <section v-if="page==='plans'" class="wb-panel"><div class="wb-panel-title"><div><h3>观察计划与结果对照</h3><span>保存当时的规则、报价与理由，避免事后修改依据。</span></div><button class="wb-button" @click="loadPlans">刷新</button></div><div v-if="!plans.length" class="wb-empty">还没有观察计划。在候选列表点击“＋ 观察”开始。</div><div class="wb-plan-grid"><article v-for="p in plans" :key="p.id" class="wb-plan"><div class="wb-panel-title"><strong>{{ p.name }} <small>{{ p.code }}</small></strong><span :class="tone(p.change_since_saved)">{{ pct(p.change_since_saved) }}</span></div><p>{{ p.trade_date }} · {{ p.mode==='short'?'短线':'趋势' }} · {{ phaseName(p.phase) }}</p><div class="wb-plan-prices"><span>冻结报价<b>{{ price(p.reference_price) }}</b></span><span>当前参考<b>{{ price(p.current_price) }}</b></span><span>当时评分<b>{{ p.evidence.row.score ?? '—' }}</b></span></div><p v-if="p.evidence.window">计划买入 {{ p.evidence.window.buy_date }} · 最早卖出 {{ p.evidence.window.earliest_sell_date }}<br>{{ p.evidence.reconstruction ? '事后重建的历史备选，非当时推荐' : '盘后备选，尚未成交' }}</p><p>{{ p.note || '未填写观察理由' }}</p><small>保存于 {{ formatTime(p.created_at) }}<br>对照行情 {{ p.current_source_at || '暂无' }}</small></article></div><p class="wb-footnote">价格变化以冻结报价为基准，不含交易费用，不代表真实账户收益；竞价无可核验参考价时不计算。</p></section>

      <section v-if="page==='review'" class="wb-review-grid"><div class="wb-panel"><div class="wb-panel-title"><h3>盘后证据清单</h3><button class="wb-button" :disabled="busy" @click="setPhase('review'); collect('review')">采集盘后数据</button></div><div v-for="h in data?.health.filter(x=>['stockpool_limit_up','stockpool_limit_down','stockpool_broken_board','anomaly_emotion_cycle','lhb_daily'].includes(x.api))" :key="h.api" class="wb-check-row"><span>{{ h.name }}</span><b :class="'status-'+h.status">{{ statusName(h.status) }}</b><small>{{ h.rows }}条</small></div><div class="wb-rules"><strong>复盘要回答什么？</strong><p>① 哪些方向集中涨停？ ② 涨停与炸板是否扩散？ ③ 观察名单的后续价格如何变化？ ④ 当时的数据是否完整？</p></div></div><div class="wb-panel"><h3>当日复盘笔记</h3><p class="wb-muted">笔记仅保存在当前浏览器，按日期区分。</p><textarea v-model="reviewNote" @input="saveReviewNote" placeholder="记录今天的主线、分歧、观察结果，以及下一交易日的验证条件…"></textarea><button class="wb-button" @click="exportReview">导出复盘摘要 ↓</button><p class="wb-footnote">缺项会写入摘要；未把缺失数据推断成弱市或零成交。</p></div></section>

      <section v-if="page==='data'" class="wb-panel"><div class="wb-panel-title"><div><h3>量脉接口实测</h3><span>只展示当前日期的真实采集状态；可调用不代表字段完整。</span></div><a href="https://liangmai.pro/docs" target="_blank" rel="noreferrer">官方文档 ↗</a></div><div class="wb-table-scroll"><table class="wb-table"><thead><tr><th>数据能力</th><th>用途</th><th>更新时点</th><th>实测结果</th><th>记录数</th><th>采集时间</th></tr></thead><tbody><tr v-for="h in data?.health || []" :key="h.api"><td><strong>{{ h.name }}</strong><small>{{ h.api }}</small></td><td>{{ h.use }}</td><td>{{ h.timing }}</td><td><span :class="['wb-status','status-'+h.status]">{{ statusName(h.status) }}</span><small>{{ ['error','local'].includes(h.status) ? h.message : '' }}</small></td><td>{{ h.rows }}<small v-if="h.sample_stocks">{{ h.sample_stocks }}只股票</small></td><td>{{ formatTime(h.fetched_at) }}</td></tr></tbody></table></div><div class="wb-rules"><strong>数据使用边界</strong><p>当前榜单不回填到历史日期；日线截至前一交易日；刷新页面只读本地，采集按钮才请求上游。资金流接口尚未纳入评分，避免样本净流入冒充全市场资金。</p><p>本工作台没有券商交易入口，观察计划不会产生真实订单。</p></div></section>
      <Overview v-if="page==='overview'" :day="day" :busy="busy" @open="openWorkflow" @collect="collect"/>
      <Research v-if="page==='research'" :day="day" :mode="mode" :busy="busy" @collect="collect" @stock="openResearchStock"/>
      <footer class="wb-footer"><span>观脉 · 研究与观察系统</span><span>{{ day }} / {{ mode==='short'?'短线':'趋势' }} · 源时间与采集时间分别记录</span></footer>
    </main>
    <div v-if="selected" class="wb-drawer-backdrop" @click.self="selected=null"><aside class="wb-drawer"><div class="wb-panel-title"><div><span class="wb-eyebrow">{{ selected.code }} / EVIDENCE</span><h2>{{ selected.name }}</h2></div><button class="wb-close" @click="selected=null">×</button></div><div class="wb-drawer-price"><strong>{{ phase==='pre'?'竞价截面':price(selected.price) }}</strong><span :class="tone(phase==='pre'?selected.auction_pct:selected.pct_chg)">{{ pct(phase==='pre'?selected.auction_pct:selected.pct_chg) }}</span><b class="wb-score-badge">{{ selected.score ?? '—' }}<small>规则分</small></b></div><p class="wb-muted">源时间 {{ selected.source_at || '竞价记录仅提供交易日' }} · {{ selected.freshness.label }} · {{ selected.quote_api || 'market_snapshot_all' }}</p><IntradayChart :chart="intraday" :loading="minuteLoading"/><button class="wb-button primary" :disabled="busy" @click="collect('intraday',[selected.code])">采集当日分时</button><details class="wb-daily-details"><summary>展开前复权日K线</summary><div class="wb-panel-title"><h3>历史结构</h3><button class="wb-button small" :disabled="busy || day!==today" @click="collect('watchquote',[selected.code])">单独刷新此股行情</button><button class="wb-button small" :disabled="busy" @click="collect('history',[selected.code])">补齐日线</button></div><PriceChart :items="chart"/></details><button class="wb-button small" :disabled="busy" @click="collect('execution',[selected.code])">补采此股早盘分钟线与涨跌停价</button><p class="wb-footnote">前复权日线，截止前一交易日；不以当日未收盘K线计算均线。</p><h3>为什么得到这个分数？</h3><div v-if="!selected.factors.length" class="wb-rules">至少需要65条连续至前一交易日的有效日线。数据不足，暂不生成趋势评分。</div><div v-for="f in selected.factors" :key="f.label" class="wb-factor"><div><strong>{{ f.label }}</strong><small>{{ typeof f.value==='number' ? number(f.value) : f.value || '字段缺失' }}</small></div><b>{{ f.points ?? '—' }} / {{ f.max }}</b><progress :value="f.points || 0" :max="f.max"/></div><div class="wb-tags"><span v-for="r in selected.risks" :key="r" class="amber">{{ r }}</span></div><h3>记录我的观察理由</h3><textarea v-model="planNote" placeholder="例如：关注板块持续性，等待回踩确认；记录失效条件…"></textarea><button class="wb-button primary full" @click="savePlan(selected,planNote)">保存观察计划与当前依据</button><p class="wb-footnote">同日、同模式、同阶段重复保存不会覆盖原始依据。</p></aside></div>
  </div>
</template>
<script setup>
import {ref,computed,watch,onMounted,onUnmounted} from 'vue'
import axios from 'axios'
import PriceChart from './PriceChart.vue'
import IntradayChart from './IntradayChart.vue'
import {triage,diversify} from './selection.js'
import Research from './Research.vue'
import Overview from './Overview.vue'
import './workbench.css'
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const day=ref(today),mode=ref('short'),phase=ref('live'),page=ref('overview'),data=ref(null),plans=ref([]),loading=ref(false),busy=ref(false),error=ref(''),message=ref(''),job=ref(null)
const navigation=[{key:'overview',icon:'◉',name:'今日工作流'},{key:'screen',icon:'◈',name:'标的工作台'},{key:'research',icon:'◷',name:'次日备选与研究'},{key:'plans',icon:'☆',name:'我的观察计划'},{key:'review',icon:'▥',name:'盘后复盘'},{key:'data',icon:'⌘',name:'数据与证据'}]
const phases=[{key:'pre',title:'竞价确认',subtitle:'前日热点 · 约9:26后'},{key:'live',title:'盘中筛选',subtitle:'行情 · 跟踪'},{key:'review',title:'盘后验证',subtitle:'结果 · 复盘'}]
const phaseName=p=>phases.find(x=>x.key===p)?.title || p
const phaseLabel=computed(()=>phaseName(phase.value))
const search=ref(''),industry=ref(''),scope=ref('all'),excludeST=ref(true),minScore=ref(0),minAmount=ref(0),minPct=ref(-30),maxPct=ref(30),minVolume=ref(0),sort=ref('score'),pageNumber=ref(1),showRules=ref(false)
const autoSync=ref(false),clockTick=ref(Date.now())
const entryLabel=computed(()=>{
 const hm=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(clockTick.value))
 if(day.value===today && data.value?.is_trade_day && hm>='10:00')return '已过10:00入场截止 · 转入持仓跟踪与次日准备'
 return data.value?.entry_policy?.label || '等待交易时段核验'
})
const intraday=ref(null),minuteLoading=ref(false)
const selected=ref(null),chart=ref([]),planNote=ref(''),reviewNote=ref('')
let sequence=0,chartSeq=0,timer=null,autoTimer=null,disposed=false
const number=v=>Number(v).toLocaleString('zh-CN',{maximumFractionDigits:2})
const price=v=>v==null?'—':Number(v).toFixed(2)
const amount=v=>v==null?'—':Math.abs(v)>=1e8?(v/1e8).toFixed(2)+'亿':Math.abs(v)>=1e4?(v/1e4).toFixed(0)+'万':number(v)
const pct=v=>v==null?'—':(v>0?'+':'')+Number(v).toFixed(2)+'%'
const tone=v=>v>0?'wb-up':v<0?'wb-down':''
const formatTime=v=>v?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—'
const statusName=s=>({ready:'返回数据',local:'本地降级',empty:'返回为空',error:'请求失败',untested:'未实测'})[s] || s
const savedCodes=computed(()=>new Set(plans.value.filter(p=>p.trade_date===day.value && p.mode===mode.value && p.phase===phase.value).map(p=>p.code)))
const ranked=computed(()=>{
 const list=(data.value?.rows || []).filter(r=>{
  const a=phase.value==='pre'?r.auction_amount:r.amount,p=phase.value==='pre'?r.auction_pct:r.pct_chg
  return (!search.value || `${r.code} ${r.name} ${r.tags.join(' ')}`.includes(search.value.trim())) && (!industry.value || r.industry===industry.value) && (!excludeST.value || !/ST|退/i.test(r.name)) && (scope.value==='all' || scope.value==='pool'&&r.in_pool || scope.value==='strong'&&r.strong || scope.value==='saved'&&savedCodes.value.has(r.code)) && (!minScore.value || r.score!=null&&r.score>=minScore.value) && (!minAmount.value || a!=null&&a>=minAmount.value*1e8) && (p==null ? minPct.value===-30&&maxPct.value===30 : p>=minPct.value&&p<=maxPct.value) && (!minVolume.value || r.volume_ratio!=null&&r.volume_ratio>=minVolume.value)
 });return list.sort((a,b)=>sort.value==='amount'?(b.amount||b.auction_amount||0)-(a.amount||a.auction_amount||0):(b.score??-1)-(a.score??-1))
})
const tier=ref('focus')
const classified=computed(()=>ranked.value.map(r=>({...r,decision:triage(r,phase.value,mode.value)})))
const focus=computed(()=>diversify(classified.value.filter(r=>r.decision.tier==='focus'),5,2))
const filtered=computed(()=>tier.value==='focus'?focus.value:tier.value==='all'?classified.value:classified.value.filter(r=>r.decision.tier===tier.value).slice(0,tier.value==='pending'?15:100))
watch(tier,()=>pageNumber.value=1)
const historyCodes=computed(()=>filtered.value.filter(r=>mode.value!=='trend' || r.score==null).slice().sort((a,b)=>(b.amount||b.auction_amount||0)-(a.amount||a.auction_amount||0)).slice(0,20).map(r=>r.code))
const pageCount=computed(()=>Math.max(1,Math.ceil(filtered.value.length/20)))
const paged=computed(()=>filtered.value.slice((pageNumber.value-1)*20,pageNumber.value*20))
watch([search,industry,scope,excludeST,minScore,minAmount,minPct,maxPct,minVolume,sort],()=>pageNumber.value=1)
const bins=computed(()=>{const bounds=[[-Infinity,-5],[-5,-2],[-2,0],[0,.00001],[.00001,2],[2,5],[5,Infinity]];return bounds.map(([lo,hi],i)=>({label:['≤-5%','-5~-2','-2~0','平盘','0~2','2~5','≥5%'][i],count:(data.value?.rows||[]).filter(r=>r.pct_chg!=null&&r.pct_chg>=lo&&r.pct_chg<hi).length,color:i<3?'#48bea0':i===3?'#5a6980':'#e77c80'}))})
const maxBin=computed(()=>Math.max(1,...bins.value.map(b=>b.count)))
const sectors=computed(()=>phase.value==='pre'?(data.value?.auction_sectors||[]).slice(0,8).map(s=>({name:s.bkName,value:pct(Number(s.jjzf))})):(data.value?.industries||[]).slice(0,8).map(s=>({name:s.name,value:s.count+'只'})))
const quoteLabel=computed(()=>{if(phase.value==='pre')return '早盘抢筹排行，非全市场';const r=data.value?.rows.find(r=>r.source_at);return r?'报价 '+r.source_at+' · '+r.freshness.label:'快照尚未就绪'})
async function openWorkflow(target,targetPhase){page.value=target;if(targetPhase&&phase.value!==targetPhase)await setPhase(targetPhase)}
function resetFilters(){search.value='';industry.value='';scope.value='all';minScore.value=0;minAmount.value=0;minPct.value=-30;maxPct.value=30;minVolume.value=0;excludeST.value=true}
function preset(){resetFilters();minScore.value=mode.value==='trend'?60:50;if(mode.value==='short'){minAmount.value=phase.value==='pre'?.1:1;minPct.value=1;maxPct.value=8;if(phase.value!=='pre')minVolume.value=1.2}}
async function load(){const seq=++sequence;loading.value=true;error.value='';try{const r=await axios.get('/api/workbench/screen',{params:{day:day.value,phase:phase.value,mode:mode.value},timeout:15000});if(seq===sequence){data.value=r.data;pageNumber.value=1;if(selected.value)selected.value=r.data.rows.find(x=>x.code===selected.value.code)||null}}catch{if(seq===sequence){data.value=null;error.value='读取失败，请确认本地服务已启动。'}}finally{if(seq===sequence)loading.value=false}}
async function loadPlans(){try{const r=await axios.get('/api/workbench/plans',{params:{day:day.value}});plans.value=r.data.items}catch{message.value='观察计划读取失败，请重试。'}}
async function reloadAll(){selected.value=null;data.value=null;resetFilters();reviewNote.value=localStorage.getItem('guanmai-review-'+day.value)||'';await Promise.all([load(),loadPlans()])}
async function setMode(v){data.value=null;mode.value=v;selected.value=null;resetFilters();await load()}
async function setPhase(v){data.value=null;phase.value=v;selected.value=null;resetFilters();await load()}
function rememberJob(value){try{if(value===undefined)return localStorage.getItem('guanmai-active-job');if(value===null)localStorage.removeItem('guanmai-active-job');else localStorage.setItem('guanmai-active-job',value)}catch{return null}}
async function collect(stage,codes=[]){if(busy.value)return;busy.value=true;message.value='';try{const r=await axios.post('/api/workbench/collect',{day:day.value,stage,codes});if(!r.data.ok)message.value=r.data.message;rememberJob(r.data.job_id);poll(r.data.job_id)}catch{busy.value=false;message.value='无法启动采集，请检查日期、所选股票与服务状态。'}}
async function poll(id){if(disposed)return;try{const r=await axios.get('/api/workbench/jobs/'+id);job.value=r.data;if(r.data.status==='running'){timer=setTimeout(()=>poll(id),1600);return}busy.value=false;rememberJob(null);const failures=r.data.results.filter(x=>!['ready','local'].includes(x.status));message.value=failures.length?`采集结束：${failures.length}项为空或失败，请在数据与证据页核对。`:'本批数据已更新。';await Promise.all([load(),loadPlans()]);if(selected.value)await loadChart(selected.value.code)}catch{busy.value=false;message.value='任务状态暂时不可读，采集可能仍在后台执行。'}}
async function loadChart(code){const id=++chartSeq;chart.value=[];intraday.value=null;minuteLoading.value=true;const results=await Promise.allSettled([axios.get('/api/workbench/history/'+code,{params:{day:day.value}}),axios.get('/api/workbench/intraday/'+code,{params:{day:day.value}})]);if(id!==chartSeq)return;chart.value=results[0].status==='fulfilled'?results[0].value.data.items:[];intraday.value=results[1].status==='fulfilled'?results[1].value.data:null;minuteLoading.value=false}
async function openResearchStock(code){const r=data.value?.rows.find(x=>x.code===code);if(r)await openStock(r);else message.value='此股缺少所选日期行情，请在标的工作台补齐。'}
async function openStock(r){selected.value=r;planNote.value='';await loadChart(r.code)}
async function savePlan(r,note=''){try{const res=await axios.post('/api/workbench/plans',{day:day.value,code:r.code,mode:mode.value,phase:phase.value,note});message.value=res.data.message;await loadPlans()}catch{message.value='保存失败，请重新载入当前证据后重试。'}}
function saveReviewNote(){try{localStorage.setItem('guanmai-review-'+day.value,reviewNote.value)}catch{message.value='浏览器无法保存笔记，请导出备份。'}}
function exportReview(){const text=`# ${day.value} 复盘摘要\n\n规则版本：${data.value?.rule_version}\n\n涨停 ${data.value?.market.limit_up??'缺失'} / 跌停 ${data.value?.market.limit_down??'缺失'} / 炸板 ${data.value?.market.broken??'缺失'}\n\n## 接口证据\n${(data.value?.health||[]).map(h=>`- ${h.name}：${statusName(h.status)}，${h.rows} 条`).join('\n')}\n\n## 笔记\n${reviewNote.value}\n\n规则排序不代表预测概率。`;const u=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download=`观脉复盘-${day.value}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
watch(page,v=>{if(v==='plans')loadPlans();if(['review','research'].includes(v)&&phase.value!=='review')setPhase('review')})
onMounted(()=>{reloadAll();const active=rememberJob();if(active){busy.value=true;poll(active)}autoTimer=setInterval(()=>{
 clockTick.value=Date.now()
 const hm=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date())
 if(autoSync.value && !busy.value && !loading.value && day.value===today && phase.value==='live' && data.value?.is_trade_day && (hm>='09:30'&&hm<='11:30'||hm>='13:00'&&hm<='15:00'))collect('quote')
},60000)})
onUnmounted(()=>{disposed=true;clearTimeout(timer);clearInterval(autoTimer)})
</script>
